<?php
$conf=array (
  'siteName' => '酱醋茶 | 一个程序员的日常 | seosite',
  'siteURL' => 'http://www.seosite.cn',
  'authorName' => 'Earl',
  'authorIntro' => '酱醋茶 | 一个程序员的日常 | seosite',
  'siteKey' => '7b89e88bc3833a084adeeeb3a3935db44dc3aa3d',
  'timeZone' => 'Asia/Shanghai',
  'pageCache' => '1',
  'commentOpt' => '3',
  'comFrequency' => '',
  'comPerLoad' => '',
  'siteTheme' => 'default',
  'siteLang' => 'zh-cn',
  'perPage' => '10',
  'linkPrefixIndex' => 'index.php',
  'linkPrefixCategory' => 'category.php',
  'linkPrefixArticle' => 'read.php',
  'linkPrefixTag' => 'tag.php',
  'social-sina-weibo' => 'http://weibo.com/V5guoerchao/',
  'social-weixin' => 'page.php/ccit_guo',
  'social-twitter' => 'https://twitter.com/seosite_earl',
  'social-facebook' => '',
  'social-douban' => 'https://www.douban.com/people/144425494/',
  'social-instagram' => '',
  'social-renren' => '',
  'social-linkedin' => '',
  'externalLinks' => 'http%3A%2F%2Fccitnet.cn="NET技术服务社"
http%3A%2F%2Fwww.qq977.com="山隈的博客"
http%3A%2F%2Fguochao.seosite.cn="NeilKwok"',
);